In [4]:
import pandas as pd
import numpy as np
import random
from faker import Faker

In [5]:
fake = Faker()

In [ ]:
career_profiles = {
    "Data Scientist": {
        "skills": [
            "python", "sql", "pandas", "numpy",
            "machine learning", "statistics", "data visualization"
        ],
        "education": [
            "BTech CSE", "MCA", "MSc Data Science", "BSc Statistics"
        ],
        "interests": [
            "ai", "data analytics", "research", "machine learning"
        ]
    },

    "Frontend Developer": {
        "skills": [
            "html", "css", "javascript", "react",
            "bootstrap", "ui design"
        ],
        "education": [
            "BCA", "BTech IT", "MCA"
        ],
        "interests": [
            "web design", "frontend", "ui ux", "creative coding"
        ]
    },

    "Backend Developer": {
        "skills": [
            "python", "java", "sql", "django",
            "flask", "api development"
        ],
        "education": [
            "BTech CSE", "MCA", "BCA"
        ],
        "interests": [
            "backend systems", "databases", "server architecture"
        ]
    },

    "Machine Learning Engineer": {
        "skills": [
            "python", "tensorflow", "pytorch",
            "machine learning", "deep learning", "numpy"
        ],
        "education": [
            "BTech CSE", "MTech AI", "MCA"
        ],
        "interests": [
            "ai", "deep learning", "automation"
        ]
    },

    "Cloud Engineer": {
        "skills": [
            "aws", "docker", "linux", "kubernetes",
            "terraform", "networking"
        ],
        "education": [
            "BTech CSE", "BTech IT", "MCA"
        ],
        "interests": [
            "cloud computing", "infrastructure", "devops"
        ]
    },

    "Cybersecurity Analyst": {
        "skills": [
            "network security", "ethical hacking", "linux",
            "penetration testing", "python"
        ],
        "education": [
            "BTech CSE", "BSc Cybersecurity", "MCA"
        ],
        "interests": [
            "security", "ethical hacking", "cyber defense"
        ]
    },

    "Business Analyst": {
        "skills": [
            "excel", "sql", "power bi",
            "data analysis", "communication"
        ],
        "education": [
            "MBA", "BBA", "BCom"
        ],
        "interests": [
            "business strategy", "analytics", "reporting"
        ]
    },
    "DevOps Engineer": {
        "skills": [
            "docker", "jenkins", "linux", "aws",
            "kubernetes", "ci cd"
        ],
        "education": [
            "BTech CSE", "MCA"
        ],
        "interests": [
            "automation", "deployment", "infrastructure"
        ]
    },

    "AI Engineer": {
        "skills": [
            "python", "machine learning", "deep learning",
            "nlp", "tensorflow", "llms"
        ],
        "education": [
            "BTech CSE", "MTech AI", "MCA"
        ],
        "interests": [
            "artificial intelligence", "nlp", "automation"
        ]
    },

    "Full Stack Developer": {
        "skills": [
            "html", "css", "javascript", "react",
            "node js", "mongodb", "express"
        ],
        "education": [
            "BTech CSE", "BCA", "MCA"
        ],
        "interests": [
            "web development", "frontend", "backend"
        ]
    }
}

In [25]:
def generate_candidate(career):
    profile = career_profiles[career]

    max_skills = len(profile["skills"])
    num_skills = random.randint(3, max_skills)

    selected_skills = random.sample(profile["skills"], num_skills)

    noise_count = random.randint(0, 2)
    noise_skills = random.sample(common_skills, noise_count)

    all_skills = list(set(selected_skills + noise_skills))

    education = random.choice(profile["education"])

    mixed_interests = profile["interests"] + [
        "technology",
        "innovation",
        "problem solving"
    ]

    interest = random.choice(mixed_interests)

    experience = random.randint(0, 8)

    return {
        "skills": " ".join(all_skills),
        "education": education,
        "interests": interest,
        "experience": experience,
        "career": career
    }

In [26]:
generate_candidate("Data Scientist")

{'skills': 'python data visualization git sql pandas machine learning',
 'education': 'MSc Data Science',
 'interests': 'ai',
 'experience': 6,
 'career': 'Data Scientist'}

In [27]:
generate_candidate("AI Engineer")

{'skills': 'tensorflow python deep learning',
 'education': 'MTech AI',
 'interests': 'technology',
 'experience': 8,
 'career': 'AI Engineer'}

In [36]:
dataset = []

for career in career_profiles:
    for _ in range(100):
        dataset.append(generate_candidate(career))

df = pd.DataFrame(dataset)

In [37]:
df = pd.DataFrame(dataset)

In [38]:
df.head()

,skills,education,interests,experience,career
0,numpy git statistics linux pandas machine lear...,BTech CSE,machine learning,3,Data Scientist
1,pandas numpy data visualization aws,BSc Statistics,machine learning,7,Data Scientist
2,data visualization numpy statistics linux sql ...,MSc Data Science,research,1,Data Scientist
3,python data visualization numpy statistics pro...,BTech CSE,problem solving,5,Data Scientist
4,python numpy statistics communication sql pand...,MCA,innovation,5,Data Scientist

In [39]:
df.tail()

,skills,education,interests,experience,career
995,node js css aws javascript mongodb sql html ex...,MCA,backend,1,Full Stack Developer
996,node js css javascript mongodb html express react,BCA,web development,1,Full Stack Developer
997,node js aws git react express css,MCA,innovation,5,Full Stack Developer
998,html css mongodb linux,BCA,problem solving,0,Full Stack Developer
999,css git docker html react,BTech CSE,technology,5,Full Stack Developer

In [40]:

df.shape

(1000, 5)

In [41]:
df["career"].value_counts()

career
Data Scientist               100
Frontend Developer           100
Backend Developer            100
Machine Learning Engineer    100
Cloud Engineer               100
Cybersecurity Analyst        100
Business Analyst             100
DevOps Engineer              100
AI Engineer                  100
Full Stack Developer         100
Name: count, dtype: int64

In [42]:
df.to_csv("../data/raw/career_dataset.csv", index=False)

In [43]:
common_skills = [
    "python",
    "sql",
    "git",
    "linux",
    "communication",
    "problem solving",
    "docker",
    "aws"
]

In [44]:
df.head(10)

,skills,education,interests,experience,career
0,numpy git statistics linux pandas machine lear...,BTech CSE,machine learning,3,Data Scientist
1,pandas numpy data visualization aws,BSc Statistics,machine learning,7,Data Scientist
2,data visualization numpy statistics linux sql ...,MSc Data Science,research,1,Data Scientist
3,python data visualization numpy statistics pro...,BTech CSE,problem solving,5,Data Scientist
4,python numpy statistics communication sql pand...,MCA,innovation,5,Data Scientist
5,python data visualization numpy statistics sql...,BTech CSE,problem solving,2,Data Scientist
6,python data visualization numpy git statistics...,BSc Statistics,technology,7,Data Scientist
7,python numpy machine learning statistics,BTech CSE,ai,6,Data Scientist
8,python data visualization numpy git statistics...,BSc Statistics,data analytics,1,Data Scientist
9,python data visualization numpy statistics com...,BSc Statistics,technology,1,Data Scientist

In [45]:
df.to_csv("../data/raw/career_dataset.csv", index=False)